name: Release NuGet Package

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore src/Locksmith.NET.csproj

      - name: Build
        run: dotnet build src/Locksmith.NET.csproj --configuration Release --no-restore

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Pack NuGet
        run: dotnet pack src/Locksmith.NET.csproj --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ env.VERSION }}

      - name: Push to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
